export const products = [
  {
    id: 1,
    title: "Wooden Coffee Table",
    description: "Solid wood, lightly used. Perfect for living room.",
    price: 45,
    currency: "$",
    category: "Furniture",
    categoryId: 2,
    condition: "Like New",
    images: ["https://images.unsplash.com/photo-1582582494700-c5e7b7c3535a?w=800"],
    location: {
      address: "Downtown Area",
      distance: "2.3 km away",
      coordinates: { lat: 40.7128, lng: -74.0060 }
    },
    seller: {
      id: 1,
      username: "john_doe",
      fullName: "John Doe",
      avatar: "https://i.pravatar.cc/150?img=1"
    },
    postedDate: "2024-12-20T10:30:00Z",
    views: 45,
    likes: 8,
    isActive: true,
    isFeatured: false,
    tags: ["wooden", "furniture", "living room", "coffee table"]
  },
  {
    id: 2,
    title: "Samsung 32\" LED TV",
    description: "Good condition, remote included.",
    price: 120,
    currency: "$",
    category: "Electronics",
    categoryId: 1,
    condition: "Good",
    images: ["https://images.unsplash.com/photo-1593784991095-8b46e3d38767?w=800"],
    location: {
      address: "Midtown Area",
      distance: "1.5 km away",
      coordinates: { lat: 40.7589, lng: -73.9851 }
    },
    seller: {
      id: 2,
      username: "sarah_wilson",
      fullName: "Sarah Wilson",
      avatar: "https://i.pravatar.cc/150?img=2"
    },
    postedDate: "2024-12-19T14:20:00Z",
    views: 67,
    likes: 12,
    isActive: true,
    isFeatured: true,
    tags: ["samsung", "tv", "electronics", "32 inch"]
  },
  {
    id: 3,
    title: "Mountain Bike",
    description: "Gears working, needs a little oiling.",
    price: 90,
    currency: "$",
    category: "Sports",
    categoryId: 3,
    condition: "Good",
    images: ["https://images.unsplash.com/photo-1618160708751-d5e8038eac62?w=800"],
    location: {
      address: "Park Area",
      distance: "3.1 km away",
      coordinates: { lat: 40.7831, lng: -73.9712 }
    },
    seller: {
      id: 1,
      username: "john_doe",
      fullName: "John Doe",
      avatar: "https://i.pravatar.cc/150?img=1"
    },
    postedDate: "2024-12-18T09:15:00Z",
    views: 89,
    likes: 15,
    isActive: true,
    isFeatured: false,
    tags: ["trek", "mountain bike", "sports", "cycling"]
  },
  {
    id: 4,
    title: "IKEA Study Chair",
    description: "Ergonomic design, barely used.",
    price: 35,
    currency: "$",
    category: "Furniture",
    images: ["https://images.unsplash.com/photo-1582582494654-8c0f0a93aef9?w=800"],
    location: { distance: "800 m away" },
    seller: { fullName: "John Doe", avatar: "https://i.pravatar.cc/150?img=1" },
    views: 23,
    likes: 5
  },
  {
    id: 5,
    title: "Microwave Oven",
    description: "800W, works perfectly.",
    price: 50,
    currency: "$",
    category: "Appliances",
    images: ["https://images.unsplash.com/photo-1585238342028-4e28c065c851?w=800"],
    location: { distance: "2.9 km away" },
    seller: { fullName: "Sarah Wilson", avatar: "https://i.pravatar.cc/150?img=2" },
    views: 34,
    likes: 7
  },
  {
    id: 6,
    title: "Baby Stroller",
    description: "Foldable, easy to carry.",
    price: 60,
    currency: "$",
    category: "Baby Products",
    images: ["https://images.unsplash.com/photo-1594040220888-2c02d48b3e48?w=800"],
    location: { distance: "1.1 km away" },
    seller: { fullName: "John Doe", avatar: "https://i.pravatar.cc/150?img=1" },
    views: 56,
    likes: 12
  },
  {
    id: 7,
    title: "Electric Guitar",
    description: "Well maintained, includes case.",
    price: 150,
    currency: "$",
    category: "Musical Instruments",
    images: ["https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800"],
    location: { distance: "4.2 km away" },
    seller: { fullName: "Sarah Wilson", avatar: "https://i.pravatar.cc/150?img=2" },
    views: 78,
    likes: 18
  },
  {
    id: 8,
    title: "Dining Table Set",
    description: "Includes 4 chairs, light wear.",
    price: 200,
    currency: "$",
    category: "Furniture",
    images: ["https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800"],
    location: { distance: "3.7 km away" },
    seller: { fullName: "John Doe", avatar: "https://i.pravatar.cc/150?img=1" },
    views: 92,
    likes: 22
  },
  {
    id: 9,
    title: "Road Bike Helmet",
    description: "Lightweight, comfortable fit.",
    price: 25,
    currency: "$",
    category: "Sports",
    images: ["https://images.unsplash.com/photo-1581089781785-603411fa81e5?w=800"],
    location: { distance: "1.9 km away" },
    seller: { fullName: "Sarah Wilson", avatar: "https://i.pravatar.cc/150?img=2" },
    views: 15,
    likes: 3
  },
  {
    id: 10,
    title: "Smartphone - 128GB",
    description: "Works fine, minimal scratches.",
    price: 300,
    currency: "$",
    category: "Electronics",
    images: ["https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=800"],
    location: { distance: "2.0 km away" },
    seller: { fullName: "John Doe", avatar: "https://i.pravatar.cc/150?img=1" },
    views: 134,
    likes: 28
  },
  {
    id: 11,
    title: "Office Desk",
    description: "Spacious, with drawers.",
    price: 80,
    currency: "$",
    category: "Furniture",
    images: ["https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=800"],
    location: { distance: "900 m away" },
    seller: { fullName: "Sarah Wilson", avatar: "https://i.pravatar.cc/150?img=2" },
    views: 67,
    likes: 14
  },
  {
    id: 12,
    title: "Winter Jacket",
    description: "Warm and waterproof.",
    price: 70,
    currency: "$",
    category: "Clothing",
    images: ["https://images.unsplash.com/photo-1618354691373-d851c3c6877b?w=800"],
    location: { distance: "1.2 km away" },
    seller: { fullName: "John Doe", avatar: "https://i.pravatar.cc/150?img=1" },
    views: 43,
    likes: 9
  },
  {
    id: 13,
    title: "Vacuum Cleaner",
    description: "Powerful suction, bagless.",
    price: 85,
    currency: "$",
    category: "Appliances",
    images: ["https://images.unsplash.com/photo-1581579188871-45ea61f2a0c8?w=800"],
    location: { distance: "2.4 km away" },
    seller: { fullName: "Sarah Wilson", avatar: "https://i.pravatar.cc/150?img=2" },
    views: 58,
    likes: 11
  },
  {
    id: 14,
    title: "Running Shoes",
    description: "Lightweight, barely worn.",
    price: 40,
    currency: "$",
    category: "Sports",
    images: ["https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800"],
    location: { distance: "1.8 km away" },
    seller: { fullName: "John Doe", avatar: "https://i.pravatar.cc/150?img=1" },
    views: 29,
    likes: 6
  },
  {
    id: 15,
    title: "Bluetooth Speaker",
    description: "Clear sound, portable.",
    price: 35,
    currency: "$",
    category: "Electronics",
    images: ["https://images.unsplash.com/photo-1598327105666-5b89351aff97?w=800"],
    location: { distance: "2.5 km away" },
    seller: { fullName: "Sarah Wilson", avatar: "https://i.pravatar.cc/150?img=2" },
    views: 72,
    likes: 16
  },
  {
    id: 16,
    title: "Bookshelf",
    description: "5-tier wooden shelf.",
    price: 55,
    currency: "$",
    category: "Furniture",
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800"],
    location: { distance: "3.0 km away" },
    seller: { fullName: "John Doe", avatar: "https://i.pravatar.cc/150?img=1" },
    views: 38,
    likes: 8
  },
  {
    id: 17,
    title: "Camping Tent",
    description: "Sleeps 4, waterproof.",
    price: 110,
    currency: "$",
    category: "Sports",
    images: ["https://images.unsplash.com/photo-1508873535684-277a3cbcc4e2?w=800"],
    location: { distance: "4.5 km away" },
    seller: { fullName: "Sarah Wilson", avatar: "https://i.pravatar.cc/150?img=2" },
    views: 84,
    likes: 19
  },
  {
    id: 18,
    title: "Baby Crib",
    description: "Sturdy, safe, and comfortable.",
    price: 150,
    currency: "$",
    category: "Baby Products",
    images: ["https://images.unsplash.com/photo-1605236453809-2a7b3b20d61f?w=800"],
    location: { distance: "1.4 km away" },
    seller: { fullName: "John Doe", avatar: "https://i.pravatar.cc/150?img=1" },
    views: 96,
    likes: 21
  },
  {
    id: 19,
    title: "Kitchen Blender",
    description: "Multiple speed settings.",
    price: 45,
    currency: "$",
    category: "Appliances",
    images: ["https://images.unsplash.com/photo-1590080876275-2a7db9c3a9d2?w=800"],
    location: { distance: "2.2 km away" },
    seller: { fullName: "Sarah Wilson", avatar: "https://i.pravatar.cc/150?img=2" },
    views: 51,
    likes: 10
  },
  {
    id: 20,
    title: "Leather Backpack",
    description: "Stylish and spacious.",
    price: 95,
    currency: "$",
    category: "Accessories",
    images: ["https://images.unsplash.com/photo-1533652809136-1c07f1f26c9e?w=800"],
    location: { distance: "1.6 km away" },
    seller: { fullName: "John Doe", avatar: "https://i.pravatar.cc/150?img=1" },
    views: 63,
    likes: 13
  }
];
